### ISSUE TITLE
[Crash]Crash with tetra-1.18.2-4.9.4

### ISSUE THREAD

**Issue by 6371peter** [AceTheEldritchKing/art_of_forging#11]
Version
Forge-1.18.2-40.1.80
art_of_forging-1.5.1-1.18.2
tetra-1.18.2-4.9.4
mutil-1.18.2-4.5.0

Crash Report:[https://pastebin.com/kHdMMrPg](https://pastebin.com/kHdMMrPg)

**Comment by AceTheEldritchKing** [comment]
Hi!
I was looking through the crash log and I have an idea of how it happened. Do you have any other information to help recreate this issue?

**Comment by 6371peter** [comment]
> Hi! I was looking through the crash log and I have an idea of how it happened. Do you have any other information to help recreate this issue?

Reproduction Steps
 1.Download Forge 1.18.2 40.1.80 and mod
 2.Use HMCL run the game(java version:jdk-18.0.1.1)
 3.Then game crash

Crash Report:[https://pastebin.com/pWicAj25](https://pastebin.com/pWicAj25)

**Comment by Smartin-b** [comment]
This should be resolved by the new AoF version, right?
