### ISSUE TITLE
Game crashing when loading world

### ISSUE THREAD

**Issue by Simpcraft** [AceTheEldritchKing/art_of_forging#13]
Hello! ive seen your mod looking for additions for my server!
I tried loading the mod and making a single player world but it seems everytime i try loading the world it crashes.
I used the following mods.
- Art of forging 1.5.3
- JEI
- MULTI 4.5.0
- OPTIFINE
- TETRA 4.9.5
- TETRA PACK 0.5.3

**Comment by ambientNexus** [comment]
Try it without optifine.
