### ISSUE TITLE
1.5.3-1.18.2 Quarry Hammer is non-functional

### ISSUE THREAD

**Issue by WhynautTV** [AceTheEldritchKing/art_of_forging#14]
after updating tetra, art of forging, and mutil to their latest versions the quarry hammer is only breaking individual blocks.

tetra-1.18.2-4.10.0
mutil-1.18.2-4.5.0
art_of_forging-1.5.3-1.18.2

**Comment by AceTheEldritchKing** [comment]
I found out about this issue recently! Looking into it; I will close this issue once it is fixed
