### ISSUE TITLE
Honing and durability loss on canes

### ISSUE THREAD

**Issue by wqferr** [AceTheEldritchKing/art_of_forging#16]
### Feature description

Canes currently have no durability limit and no reason to be repaired, and no useful hones. I would like to suggest a (low) durability cost of using a cane to walk, which would also progress towards honing.

With respect to honing, I only have two suggestions: speed boost and step assist.

### How it improves the player experience

This makes canes more fun, adds some progression to them, and gives us reason to make canes out of anything other than wood.

**Comment by StellaBiscuit** [comment]
Adding onto this, I think the cane's material should also influence the mouvement speed
