### ISSUE TITLE
Alex's Mobs Compat Serrated Tooth Shield Spike is Missing a translation key and texture

### ISSUE THREAD

**Issue by f-raZ0R** [AceTheEldritchKing/art_of_forging#23]
The compat 'recipe' (if you'd even call it that) spike material of a serrated shark tooth, is completely missing any textures, and has an untranslated raw name of "tetra.variant.spike/" (presumably the rest of it is just cut off).

**Comment by AceTheEldritchKing** [comment]
I meant to remove the recipe; will fix.
