### ISSUE TITLE
Arcane Artifact doesn't do anything (except the effect ones)

### ISSUE THREAD

**Issue by zhmstr** [AceTheEldritchKing/art_of_forging#28]
I've got some Arcane Artifact from dungeons and i tried to modify them and add extra mana with it, but it doesn't add mana when equipped on curio slot.

Also aswell, it doesn't increase the curio/belt/charm slots. The only effect it does is the internal orb effect.

![image](https://github.com/AceTheEldritchKing/art_of_forging/assets/107897693/21e038ba-df76-45ae-98c4-2700f52c116d)

**Comment by AceTheEldritchKing** [comment]
I'm not familiar with Arcane artifacts, is that material added in by another addon? Curio effects are registered differently than normal Tetra effects, which would be why it isn't working. As well, the curios do not increase slots, I should have removed the lang that says that. Only the orb component should be doing effects.

**Comment by zhmstr** [comment]
> I'm not familiar with Arcane artifacts, is that material added in by another addon? Curio effects are registered differently than normal Tetra effects, which would be why it isn't working. As well, the curios do not increase slots, I should have removed the lang that says that. Only the orb component should be doing effects.

The material is added by [Iron's Spells 'n Spellbooks](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks), it already has support/compat with Tetra mod.

Also, imo I think it's too overpowered to add stuff that increase slots. Maybe you should turn one casing to one that amplifies the orb effect + material effects but no extra slot, while for others casing, cap it to increase only once (no multiples is allowed).

**Comment by AceTheEldritchKing** [comment]
I can make a PR for curio support then. It shouldn't be too hard to make it compatible with AoF curios.

I might consider those options, however, I am only focusing on bug fixes right now rather than content as I am no longer working on Tetra addons.
