### ISSUE TITLE
how do you get the Dragon Soul 1.19.2

### ISSUE THREAD

**Issue by OrionsExile** [AceTheEldritchKing/art_of_forging#29]
there's no information about the item's existance even and no showing of how to obtain it, along side quite a few other items.

**Comment by AceTheEldritchKing** [comment]
Kill the Ender Dragon. I've been meaning to make a wiki, however, I've been
busy with work and irl stuff that I just haven't gotten the time to do so.

**Comment by OrionsExile** [comment]
I've killed it 3 times, what's the drop chance?

**Comment by AceTheEldritchKing** [comment]
Roughly an 80% chance to drop

**Comment by AceTheEldritchKing** [comment]
If my math is mathing

**Comment by OrionsExile** [comment]
okay then that's a bit odd, i have a looting 4 sword (quark) and no drop, I'll keep trying

**Comment by OrionsExile** [comment]
welp, thank you i just got one
