### ISSUE TITLE
[Crash] Forge 1.20.1 Initialization Error - Client crash on loading.

### ISSUE THREAD

**Issue by NovaLynxie** [AceTheEldritchKing/art_of_forging#37]
Hi there!

I am having trouble getting Art of Forging working normally, the game refuses to load at all.
Trying to run the mod with Tetra seems to just crash on start up with a very confusing error message.
Is there a specific version that Art of Forging requires to run normally? I seem to be either mod conflicts or straight up game crashes.
Testing the mods independently in a test setup indicates this may be a potential issue with either specific Tetra or Curios version dependency. Please can someone confirm this?

Steps to reproduce:
1. Install Forge for 1.20.1 (using recommended version)
2. Install Tetra and Art of Forging, including relevant dependencies for both mods. 
3. Run the game and observe loading progress up till game crashes.
4. Check crash logs. Should either come up as a "fml" or "client" crash log post loading/crash.

Crash Log: [crash-2024-06-24_11.28.23-client.txt](https://github.com/user-attachments/files/15953787/crash-2024-06-24_11.28.23-client.txt)

Version Information:
Minecraft 1.20.1
Forge (47.3.0)
Art of Forging (1.8-1.20.1)
Curios API (11.1.118)
mutil (6.1.1)
Tetra (6.3.0)

**Comment by NovaLynxie** [comment]
Update from testing, downgraded Tetra from 6.3.0 to 6.2.0 and game now loads normally. Assuming that something changed between the two versions, because of this Art of Forging does not currently support Tetra's latest version as of right now.
Crash log indicates the following is the cause, extracted from the crash log file posted in this issue:
```log
Suppressed: net.minecraftforge.fml.ModLoadingException: Art Of Forging (art_of_forging) encountered an error during the common_setup event phase
§7java.lang.NoSuchMethodError: 'void se.mickelus.tetra.module.schematic.RemoveSchematic.registerRemoveSchematics(se.mickelus.tetra.items.modular.IModularItem, java.lang.String)'
```

**Comment by FranFkntastic** [comment]
Also having this issue, with the exact same noSuchMethodError.

**Comment by AceTheEldritchKing** [comment]
Downgrade from Tetra 6.3.0 to 6.2.0. Unfortunately, this is not an easy fix and AoF may not be updated to fix this. Certain classes were removed which breaks AoF

**Comment by FranFkntastic** [comment]
Figured as much. Keeping my fingers crossed because AoF is very cool :)
