### ISSUE TITLE
CRASH when looking at workbench with "curios artitfact" in hand.

### ISSUE THREAD

**Issue by euryale134** [AceTheEldritchKing/art_of_forging#38]
I tried again with only necessary mods, but it happened again.

[crash-2024-07-22_21.03.18-client.txt](https://github.com/user-attachments/files/16333632/crash-2024-07-22_21.03.18-client.txt)

**Comment by AceTheEldritchKing** [comment]
Can you give some more information? Like the versions of the mod? As well as your mod list?

**Comment by euryale134** [comment]
> Can you give some more information? Like the versions of the mod? As well as your mod list?

The crash report contains this information.

Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tetra-1.20.1-6.2.0.jar                            |tetra                         |tetra                         |6.2.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		curios-forge-5.4.7+1.20.1.jar                |Curios API                    |curios                        |5.4.7+1.20.1        |DONE      |Manifest: NOSIGNATURE
		mutil-1.20.1-6.1.1.jar                    |mutil                         |mutil                         |6.1.1               |DONE      |Manifest: NOSIGNATURE
		art_of_forging-1.8.2-1.20.1.jar                   |Art Of Forging                |art_of_forging                |1.8.2-1.20.1        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: bb93dbc9-b16d-4349-98ac-b5b949690546
	FML: 47.3
	Forge: net.minecraftforge:47.3.5
