### ISSUE TITLE
Throwing Knife Scrolls generated from dungeon chest mistakenly reference Halberd Scroll

### ISSUE THREAD

**Issue by Tyrus5255** [AceTheEldritchKing/art_of_forging#4]
![image](https://user-images.githubusercontent.com/32311201/168406137-f47f700f-acf7-4ba2-a03e-a52ba022b2b4.png)

normal Throwing Knife scrolls can be spawned in just fine, however any scrolls found normally within dungeon chests instead act as halberd scrolls.

**Comment by AceTheEldritchKing** [comment]
Noted! I will fix this as soon as I can
This will be closed once the fix goes through :)
