### ISSUE TITLE
Art of Forging crashing when loading on 1.20.1

### ISSUE THREAD

**Issue by HTMLDevelopment** [AceTheEldritchKing/art_of_forging#40]
[crash-2024-12-10_00.30.01-fml.txt](https://github.com/user-attachments/files/18083241/crash-2024-12-10_00.30.01-fml.txt)
Using the latest version of Tetra and Art of Forging btw

**Comment by AceTheEldritchKing** [comment]
Downgrade to Tetra version 6.4.0 as AoF is not compatible with higher versions (should be noted on the mod page now)
I cannot give you an estimate on when it will be fixed or if it will be fixed since I haven't been able to find a proper solution to this issue yet
