### ISSUE TITLE
[suggestion]: more mining tool types for 2 headed tools

### ISSUE THREAD

**Issue by BamsyTheSergal** [AceTheEldritchKing/art_of_forging#7]
something like a full on shovel head for 2 headed tools, sorta like an entrenching tool or some sort of rake

**Comment by AceTheEldritchKing** [comment]
Hello!
I believe base Tetra already has something similar to this. There is the adze module which covers shovel and axe functionality. I may take this into consideration, but base Tetra has pretty much a good amount of tool types already covered for double heads.
